[build-system]
requires = ["setuptools>=80", "setuptools-scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui-worker"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "packaging~=25.0",
    "tomlkit~=0.13",
]

[tool.setuptools.dynamic]
version = {attr = "main.__version__"}

[tool.setuptools-scm]
